### PR TITLE
MDAL support

### PR DESCRIPTION
**Pull request by wfvining**
This merge adds MDAL support to functions in marfs_ops and common.  I believe most cases of POSIX functions being used directly instead of indirectly through the MDAL have been addressed. I did not find any more after second quick read through of the code.

### CODE REVIEW

**Comment by jti-lanl** [comment]
Looks great.  Trying to figure out how to do a local pull for testing.  The github commands don't seem to work.

**Comment by wfvining** [comment]
Jeff, I think I messed up the standard workflow. I'll see if I can go back and correct the workflow to make this easier to test.

**Comment by jti-lanl** [comment]
No need.  Thanks.  I've got it now.  I had to pull it via https, for some reason.

**Comment by jti-lanl** [comment]
Tested this a little, in private.  Testing turned up [pftool issue 31](https://github.com/pftool/pftool/issues/31).  I'll address that (for starters) with a follow-up patch, after this.

**Comment by jti-lanl** [comment]
Done.

**Pull request merged**
